# Generated by Django 5.2.5 on 2025-08-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employees_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
